### PR TITLE
Parts not properly loaded on flight load

### PR DESCRIPTION
**Pull request by omgnull**
A title says

http://cloud-4.steampowered.com/ugc/3296942373772327746/143F4E8374831D90E952E9483AC796D29D91932E/

### CODE REVIEW

**Comment by omgnull** [comment]
Could models have inner parts created with different axes?

[Start state](http://cloud-4.steampowered.com/ugc/3296942373784472140/E2CDB10CA2331B110A227FC3726CCE47FDA751E7/)

[Loading state](http://cloud-3.steampowered.com/ugc/3296942373784473487/338B5DABB5E25EFAF6992B8E360BECAD4C271849/)

**Comment by omgnull** [comment]
@sirkut I think its not working et. Also try to build from https://github.com/omgnull/InfernalRobotics/tree/fix_static_base i had applied some changes from https://github.com/taniwha-qf/InfernalRobotics/blob/partmodule/InfernalRobotics/InfernalRobotics/Toggle.cs

**Comment by sirkut** [comment]
Alright. Checking out this branch.

**Comment by sirkut** [comment]
I notice that node attached hinges work fine during a saved state but a surface attached hinge fails and has it's fixedMesh rotated.

**Comment by omgnull** [comment]
Could you please add screenshots?

**Comment by sirkut** [comment]
Sure. As you can see here. The first image is the initial movement. Then I saved the game, went to the Space Center then went back to the launch pad. You will notice that both the adjustablerail & the closed hinge's fixedMesh are placed incorrectly (marked by the red arrows).
screenshot4

2014-04-21 15_04_19-screenshot5 png - irfanview

**Comment by sirkut** [comment]
Also: By comparing the quicksave.sfs data before movement and after movement you'll also see that the position value gets shifted by the value of the trans or rot parameter that is stored within the quicksave.sfs

**Pull request merged**
