### PR TITLE
fix loading static mesh postion and add test crafts folder

### PR DESCRIPTION
**Pull request by omgnull**
opposite connections not supported
for issue #4

### CODE REVIEW

**Comment by sirkut** [comment]
Ah yes. This bug has always been present. I've always suggested attaching the "bottom" of each part first because this is how the plugin is implemented. The reason this happens is because each model is composed of 2 uniquely named meshes. In the CFG there is a variable called fixedMesh. This denotes which mesh will stay still while the other mesh is free to move. Due to the implementation I don't think there is no way around this "bug." Unless we can determine somehow to know that the fixedMesh is being connected first to a part.

**Comment by omgnull** [comment]
I'm currently tracking dock/undock bug (http://forum.kerbalspaceprogram.com/threads/37707?p=1109257&viewfull=1#post1109257). It seems the ksp joint restores forces.

**Comment by sirkut** [comment]
I tested the craft example out and I'm not experiencing the issue. Both crafts work fine during dock and undocking.

**Comment by sirkut** [comment]
I will say that two docked craft however are experiencing issues as described in the thread.

**Pull request merged**
