### PR TITLE
Feature/draganddrop

### PR DESCRIPTION
**Pull request by TriggerAu**
Hiya, Here's the pull request for the drag and drop functionality for IR Group editor windows. I had to rewrite the GIT history to make it get the changes correctly

The list of stuff for any logs you keep is:
- Drag and Drop of Servos in Editor and Group Editor
- Drag and Drop on empty group
- Pane scrolls when you drag to top or bottom of window
- Set a variable for window width and tweaked it
- Set a variable for button height and tweaked it
- Changed the Arrows to arrows

I'd guess you dont need the project file changes, but I'll leave the merge to you

### CODE REVIEW

**Comment by Squelch** [comment]
Hi guys,
I had intended a fix for the Group editor auto sizing issue, but unfortunately was called away. I do see that this pull request makes my intentions redundant, and I happily defer to @TriggerAU. However, there are a number of merge conflicts caused by the history rewrite. May I help in cleaning up the history for a clean merge into master?

**Comment by TriggerAu** [comment]
I'm somewhat of a GIT noob myself. From my first brush I'm pretty sure the conflicts are - the sln, csproj and the utilities file where @sirkut removed the connected resources chunk and I edited it to do the testing. I probably should have remerged from master before the pull request, but I didnt notice it :( . Maybe I should do that and repush before a merge happens - that would make cleaning up much easier no?

@Squelch - you dont need to defer to me you could well have much better ideas - you can see the pull request in action here - https://www.youtube.com/watch?v=tdKMcmQBwEo . If I can add something in there or help you add something then PM me on the forum.

**Comment by Squelch** [comment]
Pull before merge is always preferred, and any conflicts should be easy to see. Git is pretty unforgiving of history changes, and it can get messy. The .sln, and some of the other build environment files can be safely ignored in my opinion. - add to gitignore?

I had found that the resize issue was down to how GuiLayout was nested, but I also planned on some other changes further along. My repo was on an external drive that got reused while I was away. I never synced with GitHub, so the changes are lost. Your work looks like it's addressed that issue anyhow.

 Drag and drop is far more intuitive, and great work btw!

**Comment by TriggerAu** [comment]
Thanks for the tips @Squelch 

@sirkut I'll remerge the master branch into my fork and then push the changes again then comment - will be tomorrow though

**Comment by sirkut** [comment]
That's quite alright guys. I am patient. I'm swamped with work and flooring at the house. I'll check it tomorrow while at work. can't wait to try it.

**Comment by TriggerAu** [comment]
OK, I've remerged and cleaned it up so its only the two code files. The message now says it can be merged automagically so hopefully that's got it all sorted. Any issues let me know

**Pull request merged**
